# Generated by Django 6.0.6 on 2026-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StuID', models.IntegerField(primary_key=True, serialize=False)),
                ('StuName', models.CharField(max_length=30)),
                ('StuMarks', models.IntegerField()),
            ],
        ),
    ]
