# Generated by Django 6.0.6 on 2026-07-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.IntegerField()),
                ('StuName', models.CharField(max_length=30)),
                ('StuMarks', models.IntegerField()),
            ],
        ),
    ]
