# Generated by Django 6.0.6 on 2026-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_stuimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StuImage',
            field=models.URLField(max_length=1000),
        ),
    ]
