# Generated by Django 6.0.6 on 2026-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=30)),
                ('MovieHero', models.CharField(max_length=30)),
                ('MovieHeroine', models.CharField(max_length=30)),
                ('MovieImage', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
