# Generated by Django 6.0.6 on 2026-07-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=30)),
                ('Hero', models.CharField(max_length=20)),
                ('Heroine', models.CharField(max_length=20)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
