# Generated by Django 6.0.6 on 2026-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='StuImage',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
