# Generated by Django 6.0.6 on 2026-08-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocterID', models.IntegerField()),
                ('DoctorName', models.CharField(max_length=30)),
                ('DoctorDesc', models.CharField(max_length=30)),
            ],
        ),
    ]
