# Generated by Django 6.0.6 on 2026-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CusID', models.IntegerField()),
                ('CusName', models.CharField(max_length=30)),
                ('CusNo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
