# Generated by Django 6.0.6 on 2026-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.IntegerField()),
                ('CourseName', models.CharField(max_length=30)),
                ('CoursePrice', models.IntegerField()),
                ('CourseImage', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
