# Generated by Django 6.0.6 on 2026-07-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('PName', models.CharField(max_length=30)),
                ('PPrice', models.IntegerField()),
                ('PImage', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
