# Generated by Django 6.0.6 on 2026-07-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='EmpID',
            new_name='EmpId',
        ),
    ]
